### ISSUE TITLE
Поставить плеер по дизайну из фигмы с каунтером и стейтом для занятости

### ISSUE THREAD

**Issue by strangesound** [InfernaLEVP/re-store#11]

**Comment by strangesound** [comment]
<img width="931" alt="Screenshot 2020-11-17 at 19 49 23" src="https://user-images.githubusercontent.com/42893513/99420211-04199b00-290e-11eb-91b2-1b05f559eb8b.png">

**Comment by InfernaLEVP** [comment]
done
