### ISSUE TITLE
Правки в кнопку "Галерея"

### ISSUE THREAD

**Issue by strangesound** [InfernaLEVP/re-store#4]
1. Клик по кнопке “галерея” в мобильной версии открывает меню — поправить

2. На главной прятать кнопку “галерея” по достижении скролла

3. Кнопку “Галерея” на всех страницах сделать одинаковой — как на главной

**Comment by strangesound** [comment]
Еще на моб устройствах кнопку надо поднять, чтобы не пряталась под баром. И в меню тоже

**Comment by InfernaLEVP** [comment]
done
